name: Frontend Build & Test given cases

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        cd src/frontend
        bash run-script.sh
        ./configure
    - name: make
      run: |
        cd src/frontend
        make
#     - name: case test
#       run: |
#         cd src/frontend
#         bash case-test.sh
